# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 76d60e24e7325ad89415e97b4545c33de258ac738ef699500cafa2574727de44cff7b7291077eb8eeb3663e011e76eb251b35a7f4e9ce8c895837fe3d049f763

test:
  secret_key_base: ec45840e957086830902c6a5405ae43a2f02ca95fcc45ed3e41bde17a30fecb250b83d153c334908e5dc58a4cad99c74bb2358ff75d3d937aa157163f0493407

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
